version: "3"

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin123@hrms.2xytput.mongodb.net/?retryWrites=true&w=majority
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "4002:4000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin123@hrms.2xytput.mongodb.net/?retryWrites=true&w=majority
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run prod

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
